#!/bin/sh

export QT_QUICK_CONTROLS_STYLE=org.kde.breeze
export QT_WAYLAND_FORCE_DPI=260
export QT_QPA_PLATFORMTHEME=kde
export QT_QUICK_CONTROLS_MOBILE=1
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QT_MEDIA_BACKEND=gstreamer
